version: '3'

volumes:
  data:
  db:

networks:
  nextcloudnet:
    # empty - not needed

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      # from env file for testing
      MYSQL_ROOT_PASSWORD: my_root_pw
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: my_nextcloud_pw
#    env_file:
#      - db.secret.env
#      - db.shared.env
    networks:
      - nextcloudnet

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      # Host:Container
      - "80:80"
    volumes:
      - data:/var/www/html
    # maybe this link can be omitted due to docker-compose default network
    links:
      - db
    environment:
      # Nextcloud Settings
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: sehrgeheim456
      # DB Settings
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: my_nextcloud_pw
      # Reverse Proxy Settings
      VIRTUAL_HOST: nextcloud.avil.io
      LETSENCRYPT_HOST: nextcloud.avil.io
      LETSENCRYPT_EMAIL: bjesuiter@gmail.com
#    env_file:
#      - db.shared.env
#      - nextcloud.secret.env
    networks:
       - nextcloudnet


