version: '3'

volumes:
  main:
  files:
  db:

networks:
  nextcloudnet:
    # empty - not needed
  webproxy:
    external:
      name: webproxy

services:

  db:
    container_name: vserv-nextcloud_db
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      # from env files
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nextcloudnet

  nextcloud:
    container_name: vserv-nextcloud
    image: nextcloud
    restart: always
      # Ports MUST NOT be forwarded in production,
      # because nginx reverse proxy can connect to them on port 80 on the internal network
      # and port 80 is already occupied by the reverse proxy
#    ports:
      # Host:Container
#      - "80:80"
    volumes:
      - main:/var/www/html
      - files:/var/www/html/data
    # maybe this link can be omitted due to docker-compose default network
    links:
      - db
    environment:
      # Nextcloud Settings
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_DOMAIN}
      # DB Settings
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Reverse Proxy Settings
      VIRTUAL_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_EMAIL: bjesuiter@gmail.com
    networks:
       - nextcloudnet
       - webproxy
