###
# Dev Notes
# - needs Installed Publickey in target repo (see setup-base-services.yaml)
###
---
- name: setup-nextcloud
  hosts: epyc
  become: yes
  become_user: jb-web-services
  vars:
    # service_user_home_dir from group_vars in ansible-vserv repo
    service_root: '{{service_user_home_dir}}/services/nextcloud'
    data_root: '{{service_user_home_dir}}/data/nextcloud'

  tasks:
    - include_vars: nextcloud-vault.yaml
    - name: Clone Nextcloud Repo
      git:
        repo: 'git@github.com:bjesuiter/vserv-nextcloud.git'
        dest: '{{service_root}}'
        version: 'main'
        update: 'yes'

    - name: install dependencies from package.json
      community.general.npm:
        path: '{{service_root}}'
        state: present

    - name: Ensure that all required directories for this service exist '
      file:
        path: '{{ item }}'
        state: directory
        mode: '0770'
      loop:
        - '{{data_root}}'
        - '{{data_root}}/database'
        - '{{data_root}}/config'
        # - '{{data_root}}/files'

    # variable comes from imported vars, as described here:
    # https://gist.github.com/tristanfisher/e5a306144a637dc739e7
    # password for that encrypted file is configured in root ansible.cfg
    - name: Setup doppler cli for this project
      command:
        chdir: '{{service_root}}'
        cmd: 'doppler setup --token={{nextcloud_doppler_token}} --no-prompt'
      register: doppler_result

    # Note: On first init run `npm run first-init` to init db service, after that run `npm start` for each subsequent start
    # - name: run nextloud via npm
    #   command:
    #     cmd: npm start
    #     chdir: '{{service_root}}'
    #   register: npm_result

    - name: User Message (For initial setup)
      debug:
        msg:
          - 'For Initial Setup (if applicable):'
          - '1. `bonnie first-init` - Starts the db server and lets it initialize to avoid race-conditions later'
          - '2. `STRG + c` - Stop database if ready'
          - '3. `bonnie start-logs` - Starts complete docker-compose file and shows logs'
          - '4. Go to https://nextcloud.avil.io to finish setup'
          - '(Note: This may not work if DNS did not fully propagate through yet)'
          - 'Root Password: find in doppler dashboard'
